You don't need to flatten for Convolutional neural network and you can put in 3D models

kernel functions

first layer: finds edges or curves
second layer: looks for more complex shapes

what it does make differennt nxn grids and convolve over and over
you kinda pool over each window

In [1]:
import os
import cv2
import numpy as np
from tqdm import tqdm

In [3]:
#in preprocessing dataset you probably want to run the preprocessing once 
REBUILD_DATA = True

In [19]:
#make a class which is not necessary
class DogsVSCats():
    
    #we need to normalize the picture to be the same size which we will make 50x50
    #you can also resive but pad 
    IMG_SIZE = 50
    
    curent_dir = os.get_cwd()
    
    #make paths
    CATS = "PetImages/Cat"
    DOGS = "PetImages/Dog"
    
    CATS = os.path.join(current_dir, CATS)
    
    #labels, we are making what outputs we want and we are doing this for one hot vector
    LABELS = {CATS:0, DOGS:1}
    
    training_data = []
    
    #make counters this will be for balance
    catcount = 0
    dogcount = 0
    
    def make_training_data(self):
        
        #iterate over cats and dogs
        for label in self.LABELS:
            print(label)
            
            #list the directory
            for f in tqdm(os.listdir(label)):
                
                #use the try and except incase the images are no good
                try:
                
                    #f will be the filename we need to make each path
                    path = os.path.join(label,f)

                    #make them greyscale
                    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)

                    #now we want to resize them
                    img = cv2.resize(img, (self.IMG_SIZE, self.IMG_SIZE))

                    #append the data as a numpy image with the one hot vector method 
                    self.training_data.append([np.array(img), np.eye(2)[self.LABELS[label]]])

                    #if we have a cat
                    if label == self.CATS:

                        #add in the count for cat
                        self.catcount += 1

                    elif label == self.DOGS:
                        self.dogcount += 1
                        
                except Exception as e:
                    pass
                    
            #we'll have all of this training data now we want to shuffle it
            np.random.shuffle(self.training_data)
            np.save("training_data.npy", self.training_data)
            print("Cats:", self.catcount)
            print("Dogs:", self.dogcount)

In [20]:
if REBUILD_DATA:
    dogsvcats = DogsVSCats()
    dogsvcats.make_training_data() 

  5%|████▌                                                                             | 9/164 [00:00<00:01, 86.42it/s]

PetImages/Cat


100%|███████████████████████████████████████████████████████████████████████████████| 164/164 [00:01<00:00, 135.34it/s]
C:\Users\Diego\anaconda3\lib\site-packages\numpy\core\_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


Cats: 163
Dogs: 0
PetImages/Dog


FileNotFoundError: [WinError 3] The system cannot find the path specified: 'PetImages/Dog'

In [5]:
#we are going to one hot vector 
#for cat [1,0]
#for dog [0,1]
#to do all this we are going to use np.eye which makes diagoanls all 1
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
#what we will do is that we will make a matrix like this 
test_matrix = np.eye(2)
test_matrix

array([[1., 0.],
       [0., 1.]])

In [8]:
#and then to compare cats vs dogs we get
cat = test_matrix[0]
print(cat)

[1. 0.]


In [9]:
dog = test_matrix[1]
print(dog)

[0. 1.]


In [10]:
#its really a perfect 1 hot vector let's say we had 7th feature of 10 as our output
np.eye(10)[7]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])